model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val_loss"
  mode: "min"
  save_last: True
  dirpath: ${out_dir}

early_stopping:
  _target_: pytorch_lightning.callbacks.EarlyStopping
  monitor: "val_loss"
  mode: "min"
  patience: 10
  min_delta: 0.001
  verbose: True
