output_dir: "../Results"

# SECTION 2: GENERAL OPTIONS

use_GPU: True
save_model: True

# SECTION 3: ARCHITECTURE

z_dim: 5
hidden_layer_dims: []
non_linear: False
threshold: 0.1

# SECTION 4: TRAINING

learning_rate: 0.002
batch_size: null
n_epochs: 10
