# @package _global_

# TODO: should there be default config files for AAE and VAE?

# default parameters for AAE model
model_name: "AAE"

model:
  eps: 1e-15

discriminator:
  _target_: multiae.models.layers.Discriminator

  hidden_layer_dim: []
  bias: True
  non_linear: False

  dropout_threshold: 0 #Discriminator layer dropout

