# @package _global_

# default parameters for DVCCA model
model_name: "DVCCA"

model:
  beta: 1
  private: False

  sparse: False

encoder:
  _target_: multiae.models.layers.VariationalEncoder

  non_linear: False
  enc_dist:
    _target_: multiae.base.distributions.Normal

decoder:
  _target_: multiae.models.layers.VariationalDecoder

  non_linear: False
  init_logvar: -3

  dec_dist:
    _target_: multiae.base.distributions.Normal
