# @package _global_

# default parameters for joint AAE model
model_name: "jointAAE"

model:
  eps: 1e-15

discriminator:
  _target_: multiae.models.layers.Discriminator

  hidden_layer_dim: []
  bias: True
  non_linear: False

  dropout_threshold: 0
