# @package _global_

# default parameters for mcVAE model
model_name: "mcVAE"

model:
  beta: 1

  sparse: False
  threshold: 0.2
encoder:
  _target_: multiae.models.layers.VariationalEncoder

  non_linear: False

  enc_dist:
    _target_: multiae.base.distributions.Normal

decoder:
  _target_: multiae.models.layers.VariationalDecoder

  non_linear: False
  init_logvar: -3

  dec_dist:
    _target_: multiae.base.distributions.Normal
