# @package _global_

# default parameters for mmJSD model
model_name: "mmJSD"

model:
  private: True
  s_dim: 2

encoder:
  _target_: multiae.architectures.mlp.VariationalEncoder

  non_linear: False
  
  enc_dist:
    _target_: multiae.base.distributions.Normal

decoder:
  _target_: multiae.architectures.mlp.VariationalDecoder

  non_linear: False
  init_logvar: -3

  dec_dist:
    _target_: multiae.base.distributions.Normal
