# @package _global_

# default parameters for MVAE model
model_name: "mVAE"

model:
  beta: 1
  join_type: "PoE"  # TODO: test MeanRepresentation, set restrictions with hydra?

  sparse: False

encoder:
  _target_: multiae.models.layers.VariationalEncoder

  non_linear: False

  enc_dist:
    _target_: multiae.base.distributions.Normal

decoder:
  _target_: multiae.models.layers.VariationalDecoder

  non_linear: False
  init_logvar: -3

  dec_dist:
    _target_: multiae.base.distributions.Normal
  
