# @package _global_

# default parameters for MVTCAE model
model_name: "mvtCAE"

model:
  beta: 1
  alpha: 0.5

encoder:
  _target_: multiae.models.layers.VariationalEncoder

  non_linear: False

  enc_dist:
    _target_: multiae.base.distributions.Normal

decoder:
  _target_: multiae.models.layers.VariationalDecoder

  non_linear: False
  init_logvar: -3

  dec_dist:
    _target_: multiae.base.distributions.Normal
