# @package _global_

# default parameters for wAAE model
model_name: "wAAE"

discriminator:
  _target_: multiae.models.layers.Discriminator

  hidden_layer_dim: []  # TODO: why empty default?
  bias: True
  non_linear: False

  dropout_threshold: 0  ## TODO: this is different from sparse threshold?
