[tool.poetry]
name = "multiae"
version = "0.0.2"
description = ""
authors = ["Ana Lawry Aguila <ana.aguila.18@ucl.ac.uk>"]
readme = "README.md"
packages = [{include = "multiae"}]

[tool.poetry.dependencies]
python = "3.9"
scipy = "^1.9.0",
pytest = "^7.1.2",
pandas = "^1.4.3",
numpy = "^1.23.1",
torchvision = "^0.13.0",
torch ="^1.12.0",
pytorch-lightning = "^1.5.5",
hydra-core

[tool.setuptools.package-data]
multiae = '*yaml'
