# @package _global_

# default parameters for DVCCA model
model_name: "DVCCA"

model:
  beta: 1
  private: False

  sparse: True
  threshold: 0

encoder:
  default:
    _target_: multiviewae.architectures.mlp.VariationalEncoder

    non_linear: False

    enc_dist:
      _target_: multiviewae.base.distributions.Normal

decoder:
  default:
    _target_: multiviewae.architectures.mlp.VariationalDecoder

    non_linear: False
    init_logvar: -3

    dec_dist:
      _target_: multiviewae.base.distributions.Normal
