# @package _global_

# default parameters for joint AAE model
model_name: "jointAAE"

discriminator:
  _target_: multiviewae.architectures.mlp.Discriminator

  hidden_layer_dim: []
  bias: True
  non_linear: False

  dropout_threshold: 0 #Discriminator layer dropout

