# @package _global_

# default parameters for MVTCAE model
model_name: "mvtCAE"

model:
  beta: 1
  alpha: 0.5

encoder:
  default:
    _target_: multiviewae.architectures.mlp.VariationalEncoder

    non_linear: False

    enc_dist:
      _target_: multiviewae.base.distributions.Normal

decoder:
  default:
    _target_: multiviewae.architectures.mlp.VariationalDecoder

    non_linear: False
    init_logvar: -3

    dec_dist:
      _target_: multiviewae.base.distributions.Normal
