# @package _global_

# default parameters for gPoE mVAE model
model_name: "weighted_mVAE"

model:
  beta: 1
  private: False
  
encoder:
  default:
    _target_: multiviewae.architectures.mlp.VariationalEncoder

    non_linear: False

    enc_dist:
      _target_: multiviewae.base.distributions.Normal

decoder:
  default:
    _target_: multiviewae.architectures.mlp.VariationalDecoder

    non_linear: False
    init_logvar: -3

    dec_dist:
      _target_: multiviewae.base.distributions.Normal
