# @package _global_

# default parameters for JMVAE model
model_name: "JMVAE"

encoder:
  default:
    _target_: multiae.architectures.mlp.VariationalEncoder
    non_linear: False

    enc_dist:
      _target_: multiae.base.distributions.Normal

decoder:
  default:
    _target_: multiae.architectures.mlp.VariationalDecoder

    non_linear: False
    init_logvar: -3

    dec_dist:
      _target_: multiae.base.distributions.Normal
