
# SECTION 1: DATA MANAGEMENT

output_dir: '../year_1/project_work/Autoencoders/Results'

# SECTION 2: GENERAL OPTIONS

use_GPU: True
save_model: True

# SECTION 3: ARCHITECTURE

latent_size: 4
hidden_layers: []
non_linear: False
beta: 1
sparse: True
dropout_threshold: 0.3

# SECTION 4: TRAINING
learning_rate: 0.001
mini_batch: False
batch_size: []
n_epochs: 10000