
# SECTION 1: DATA MANAGEMENT

output_dir: '../year_1/project_work/Autoencoders/Results'

# SECTION 2: GENERAL OPTIONS

use_GPU: True
save_model: True

# SECTION 3: ARCHITECTURE

z_dim: 5
#hidden_layers: [50, 20, 10]
hidden_layer_dims: [100]
non_linear: False
beta: 1
threshold: 0.1

# SECTION 4: TRAINING

learning_rate: 0.002
batch_size: null
n_epochs: 10