# @package _global_

model:
  z_dim: 64
  s_dim: 30

encoder:
  hidden_layer_dim: [256, 256]
  non_linear: True

decoder:
  _target_: multiae.architectures.mlp.Decoder
  non_linear: True
  hidden_layer_dim: [256, 256]

  dec_dist:
    _target_: multiae.base.distributions.Bernoulli