# @package _global_

model:
  z_dim: 64
  
encoder:
  hidden_layer_dim: [512, 512]
  bias: True
  non_linear: True
  enc_dist:
    _target_: multiae.base.distributions.Normal

decoder:
  _target_: multiae.architectures.mlp.Decoder
  non_linear: True
  hidden_layer_dim: [512, 512]
  bias: True
  dec_dist:
    _target_: multiae.base.distributions.Bernoulli
