# @package _global_

model:
  z_dim: 64
  s_dim: 30

encoder:
  default:
    hidden_layer_dim: [256, 256]
    bias: True
    non_linear: True
    enc_dist:
      _target_: multiae.base.distributions.Normal

decoder:
  default:
    _target_: multiae.architectures.mlp.Decoder
    non_linear: True
    hidden_layer_dim: [256, 256]
    bias: True
    dec_dist:
      _target_: multiae.base.distributions.Bernoulli