# @package _global_

defaults:
  - override /encoder: base.yaml
  - override /decoder: base.yaml

# all parameters below will be merged with parameters from default configurations set above
# this allows you to overwrite only specified parameters

encoder:
  _target_: multiae.models.layers.Encoder

  hidden_layer_dims: [512, 256]
  bias: True
  non_linear: True
  variational: True
  enc_dist:
    _target_: multiae.utils.distributions.Normal

decoder:
  _target_: multiae.models.layers.Decoder

  hidden_layer_dims: [512, 256]
  bias: True
  non_linear: True
  variational: False
  dec_dist:
    _target_: multiae.utils.distributions.Bernoulli
