
# SECTION 1: DATA MANAGEMENT

output_dir: '../year_1/project_work/Autoencoders/Results'

# SECTION 2: GENERAL OPTIONS

use_GPU: True
save_model: True

# SECTION 3: ARCHITECTURE

latent_size: 5
hidden_layers: [100, 50, 10]
non_linear: True
beta: 4

# SECTION 4: TRAINING

learning_rate: 0.0001
mini_batch: False
batch_size: []
n_epochs: 20000