# This is a basic workflow to help you get started with Actions

name: CI
# Controls when the action will run.
on:
# Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 # This workflow contains a single job called "build"
  build:
    os: ubuntu-lateest
    runs-on: ubuntu-latest
    env:
      MODULE_NAME: multiviewae
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: 
        python -m pip install --upgrade pip
        pip install codecov
        pip install ./
        
    - name: Generate coverage report 
      run: |
        pip install pytest-cov
        pytest --cov=multiviewae ./tests/ --cov-report=xml
      if: ${{ matrix.python-version == '3.8' }}
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      if: ${{ matrix.python-version == '3.8' }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        directory: ./coverage/reports/
        fail_ci_if_error: false
        env_vars: OS,PYTHON
        files: /home/runner/work/multi-view-AE/multi-view-AE/coverage.xml
        flags: tests
        
    - name: Run Test
      run: pytest
      if: ${{ matrix.python-version == '3.7'}} | ${{ matrix.python-version == '3.9'}}
      

